version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

   build:
      commands:
        - npm install
        - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Ahmad_Almanassra_Resume.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
