version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      
  build:
    commands:
      - npm run webpack

artifcats:
  files:
    - index.html
    - favicon.ico
    - Ahmad_Almanassra_Resume.pdf
    - styles/main.css
    - images/*
