version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test

  build:
    commands:

      - npm run webpack
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
    - favicon.ico
    - Ahmad_Almanassra_Resume.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
