version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm test

  build:
    commands:
      - npm run webpack
      - echo done with build

artifacts:
  files:
    - index.html
    - favicon.png
    - Ahmad_Almanassra_Resume.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
