version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

   pre_build:
     commands:
       - npm install
       - npm test
   build:
      commands:
        - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Ahmad_Almanassra_Resume.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
